title = "Why else they are"
baseURL = "https://whyelsetheyare.netlify.app"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

DefaultContentLanguage = "vi"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-2CCCPR8E1S"
disqusShortname = "whyelsetheyare"
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Why else they are"
    weight = 1
    contentDir = "content/en"
  [languages.vi]
    title = "Toái Nguyệt ký sự"
    weight = 2
    contentDir = "content/vi"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/public/icons/tnc-logo.svg"
  site_logo = ""
  description = "The future of humanity is already determined, but your own future is determined by you."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/Ylgr"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ylgr238/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/theme.jpg"
  recent_posts_number = 5
  commentoEnable = true
